name: "Bug Report"
description: "Report a bug or an issue in map2loop"
title: "[Bug] - "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for submitting a bug report to map2loop!
        Please use this template to report a bug. Please provide as much detail as possible to help us reproduce and fix the issue efficiently.
        
  - type: input
    id: bug_title
    attributes:
      label: "Bug Title"
      description: "Provide a concise and descriptive title for the bug report."
      placeholder: "Enter the title of the bug"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: "Describe the bug you encountered. Include details on what you expected to happen and what actually happened."
      placeholder: "Enter a detailed description of the bug"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Minimal reproducible example"
      description: "Provide a minimal reproducible example with the code and data necessary to reproduce the bug."
      placeholder: "Enter the steps to reproduce the bug"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "Enter the expected behavior"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened when you encountered the bug."
      placeholder: "Enter the actual behavior"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any other context or information that may be helpful in understanding and fixing the bug."
      placeholder: "Enter any additional context"
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Specify the environment in which the bug occurred (e.g., operating system, browser, application version)."
      placeholder: "Enter the environment details"
    validations:
      required: true

  - type: checkboxes
    id: severity
    attributes:
      label: "Severity"
      description: "Select the severity level of the bug."
      options:
        - label: "Low"
        - label: "Medium"
        - label: "High"
        - label: "Critical"
    validations:
      required: true