name: "🐛 Bug Report"
description: "Report a bug or an issue in map2loop"
title: "[Bug] - "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thanks for submitting a bug report to map2loop!
        Please use this template to report a bug. Please provide as much detail as possible to help us reproduce and fix the issue efficiently.

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of map2loop and LoopProjectFile are you running? You can find this information by running `import map2loop` and `map2loop.__version__` in your python terminal or jupyter notebook. 
      placeholder: "Enter map2loop and LoopProjectFile versions"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: "Describe the bug you encountered. Include details on what you expected to happen and what actually happened."
      placeholder: "Enter a detailed description of the bug"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Minimal reproducible example"
      description: "Provide a minimal reproducible example with the code necessary to reproduce the bug. For more guidance, visit: [How to create a minimal complete reproducible example](https://forum.access-hive.org.au/t/how-to-create-a-minimal-complete-reproducible-example/843)"
      placeholder: "Enter the steps to reproduce the bug"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any other context or information that may be helpful in understanding and fixing the bug."
      placeholder: "Enter any additional context"
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Specify the environment in which the bug occurred (e.g., operating system, browser, application version)."
      placeholder: "Enter the environment details"
    validations:
      required: false



