name: "📓 Documentation Request"
description: "Help us improve map2loop documentation!"
title: "[Documentation] - "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📓 Documentation Request
        Please use this template to suggest an improvement or addition to map2loop documentation. 
        Provide as much detail as possible to help us understand and implement your request efficiently

  - type: textarea
    id: doc_details
    attributes:
      label: "Documentation Details"
      description: "Describe the documentation you would like to see. Include details on why it is needed and how it should be structured."
      placeholder: "Enter a detailed description of the documentation"
    validations:
      required: true