name: "🚀 Feature Request"
description: "Suggest a new feature or enhancement for map2loop"
title: "[Feature Request] - "
labels: ["enhancement", "feature request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Please use this template to submit your feature request. Provide as much detail as possible to help us understand and implement your request efficiently.

  - type: checkboxes
    id: input1
    attributes:
      label: "💻"
      description: |
        Check this if you would like to try and implement your vision in a PR. 
        The map2loop team will help you go through the process
      options:
        - label: Would you like to work on this feature?

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Describe the feature you would like to see. Include details on why it is needed and how it should work."
      placeholder: "Enter a detailed description of the feature"
    validations:
      required: true

  - type: textarea
    id: current_situation
    attributes:
      label: "Current Situation"
      description: "Describe the current situation and how the absence of this feature affects you."
      placeholder: "Explain the current situation and its drawbacks"
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of map2loop and LoopProjectFile are you running that doesn't have this feature? You can find this information by running `import map2loop` and `map2loop.__version__` in your python terminal or jupyter notebook. 
      placeholder: "Enter map2loop and LoopProjectFile versions"

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: "Describe how you envision the feature working. Include any specific requirements or details"
      placeholder: "Explain how the feature should work"
    validations:
      required: true

  - type: input
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any other context or information that may be helpful in understanding the feature request."
      placeholder: "Enter any additional context"
    validations:
      required: false

  - type: checkboxes
    id: affected_areas
    attributes:
      label: "Affected Areas"
      description: "Select the areas of the project that this feature request impacts."
      options:
        - label: "input data"
        - label: "project creation"
        - label: "samplers"
        - label: "sorters"
        - label: "stratigraphic column"
        - label: "data types"
        - label: "Other"
