name: "Question"
description: "Ask a question about map2loop!"
title: "[Question] - "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ## Question
        Please use this template to ask a question about applying map2loop to your data. 
        Provide as much detail as possible to help us understand and answer your question efficiently.

  - type: textarea
    id: question_details
    attributes:
      label: "Question Details"
      description: "Describe your question in detail. Include any context or background information that might be helpful."
      placeholder: "Enter the details of your question"
    validations:
      required: true

  - type: textarea
    id: relevant_code_snippets
    attributes:
      label: "Relevant code or data"
      description: "If applicable, provide any relevant code snippets or examples related to your question."
      placeholder: "Enter any relevant code snippets"
    validations:
      required: false

  - type: input
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any other context or information that may be helpful in answering your question."
      placeholder: "Enter any additional context"
    validations:
      required: false