{% set name = "map2loop" %}

package:
  name: "{{ name|lower }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"

source:
  git_url: https://github.com/Loop3D/map2loop

build:
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - loopprojectfile ==0.2.2
    - gdal
    - python
    - numpy
    - scipy
    - geopandas
    - shapely
    - networkx
    - owslib
    - map2model
    - beartype
    - pytest
    - scikit-learn

about:
  home: "https://github.com/Loop3D/map2loop"
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "Generate 3D model data using 2D maps."

extra:
  recipe-maintainers:
    - lachlangrose

channels:
  - loop3d
  - conda-forge