{% set name = "map2loop" %}

package:
  name: "{{ name|lower }}"
  version: "0.0.2"

source:
  git_url: https://github.com/Loop3D/map2loop
  git_branch: fix/dependency_checker

build:
  number: 0
  script:
  - build.sh 
  - build.bat  

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - loopprojectfile ==0.2.2
    - map2model
    - owslib
    - numpy
    - scipy
    - geopandas
    - shapely
    - networkx
    - owslib
    - beartype
    - pytest
    - scikit-learn

about:
  home: "https://github.com/Loop3D/map2loop"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Generate 3D model data from 2D maps."

extra:
  recipe-maintainers:
    - lachlangrose

channels:
  - loop3d
  - conda-forge
