{% set name = "map2loop" %}

package:
  name: "{{ name|lower }}"
  version: "0.0.2"

source:
  git_url: https://github.com/Loop3D/map2loop
  git_branch: fix/dependency_checker
  include: 
    - README.md
    - LICENSE
    - dependencies.txt
    - map2loop

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - loopprojectfile ==0.2.2
    - gdal
    - map2model
    - beartype
    - python
    - numpy
    - pandas
    - geopandas
    - shapely
    - tqdm
    - networkx
    - owslib


about:
  home: "https://github.com/Loop3D/map2loop"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Generate 3D model data from 2D maps."

extra:
  recipe-maintainers:
    - lachlangrose

channels:
  - loop3d
  - conda-forge
