{% set name = "map2loop" %}


package:
  name: "{{ name|lower }}"
#   version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"
  version: "3.0.6"

source:
  git_url: https://github.com/Loop3D/map2loop

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
    - geopandas
    - map2model
    - hjson
    - loopprojectfile
    - beartype
    - owslib
  run:
    - python
    - numpy
    - pandas
    - geopandas
    - map2model
    - hjson
    - loopprojectfile
    - beartype
    - owslib

test:
  imports:
    - map2loop
    - geopandas
    - map2model
    - hjson
    - loopprojectfile
    - beartype
    - owslib

about:
  home: "https://github.com/Loop3D/map2loop"
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "Generate 3D model data using 2D maps."

extra:
  recipe-maintainers:
    - roythomson
