{% set name = "map2loop" %}


package:
  name: "{{ name|lower }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"

source:
  git_url: https://github.com/Loop3D/map2loop

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - pandas
    - geopandas
    - shapely
    - tqdm
    - networkx
    - owslib
    - hjson
    - loopprojectfile
    - map2model
    - beartype
    - gdal=3.8.4



about:
  home: "https://github.com/Loop3D/map2loop"
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "Generate 3D model data using 2D maps."

extra:
  recipe-maintainers:
    - lachlangrose
