{% set name = "map2loop" %}


package:
  name: "{{ name|lower }}"
#   version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"
  version: "3.0.1"

source:
  git_url: https://github.com/Loop3D/map2loop-3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python
    # - pybind11
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - geopandas
    # - shapely
    # - descartes
    # - matplotlib-base
    # - networkx
    # - owslib
    # - tqdm
    - map2model
    # - mplstereonet
    - hjson
    - loopprojectfile
    - beartype

test:
  imports:
    - map2loop

about:
  home: "https://github.com/Loop3D/map2loop-3"
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "Generate 3D model data using 2D maps."

extra:
  recipe-maintainers:
    - roythomson
