name: Test Conda Build and Import


on:
  push:
  workflow_dispatch:

jobs:
  test-conda-build:
    name: Test Conda Build and Import
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.1.0
      

      - name: Install conda-build
        run: |
          conda install -y conda-build
          conda-build --version


