name: Test Conda Build and Import

on:
    workflow_dispatch:

jobs:
  test-conda-build:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout the branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Conda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10  # Specify the Python version

      # Step 3: Install conda-build
      - name: Install conda-build
        run: conda install -y conda-build

      # Step 4: Build the Conda package
      - name: Build Conda package
        run: conda-build .

      # Step 5: Create a Conda environment and install the built package
      - name: Create environment and install package
        run: |
          conda create -y -n test-env python=3.10
          source activate test-env
          conda install -y --use-local $(conda build . --output)

      # Step 6: Test the package import
      - name: Test import
        run: |
          source activate test-env
          python -c "import your_package_name"
