name: Test Conda Build and Import

on:
    workflow_dispatch:

jobs:
  test-conda-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10  

      - name: Install conda-build
        run: conda install -y conda-build

      - name: Build Conda package
        run: conda-build .

      - name: Create environment and install package
        run: |
          conda create -y -n test-env python=3.10
          source activate test-env
          conda install -y --use-local $(conda build . --output)

      - name: Test import
        run: |
          source activate test-env
          python -c "import map2loop"
