name: Test Conda Build and Import

on:
    workflow_dispatch:

jobs:
  test-conda-build:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout the branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Conda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10  # Specify the Python version

      # Step 3: Install conda-build
      - name: Install conda-build
        run: conda install -y conda-build
