name: Test Conda Build and Import

on:
  push:
  workflow_dispatch:

jobs:
  test-conda-build:
    name: Test Conda Build and Import
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(vars.BUILD_OS)}}
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS)}}
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.1.0
      

      - name: Install conda-build
        run: |
          conda install conda-build -y
          conda build conda -c loop3d -c conda-forge --test
