name: Test Conda Build and Import

on:
  push:
  workflow_dispatch:

jobs:
  test-conda-build:
    name: Test Conda Build and Import
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.1.0
        with:
          miniforge-version: latest

      - name: temporarily modify meta.yaml version
        shell: bash -l {0}
        run: |
          echo "Updating version in meta.yaml..."
          sed -i 's/^  version: .*/  version: 3.1.13local/' conda/meta.yaml
          cat conda/meta.yaml | grep "version:"

      - name: Install conda-build
        shell: bash -l {0}
        run: |
          conda update -n base conda -y
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda install conda-build -y

      - name: Build conda package
        shell: bash -l {0}
        run: |
          conda build -c conda-forge -c loop3d -c anaconda --output-folder output conda 
      
      - name: Install GDAL
        if : runner.os == 'Linux'
        shell: bash -l {0}
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
          sudo apt-get update
          sudo apt-get install -y libgdal-dev gdal-bin python3-gdal
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          python -m pip install GDAL==$(gdal-config --version)

      - name: Install GDAL windows  
        if: runner.os == 'Windows'
        shell: bash -l {0}
        run: |
          conda install -c conda-forge gdal -y

      - name: Install map2loop
        shell: bash -l {0}
        run: |
          PACKAGE_FILE=$(ls output/linux-64/map2loop*.tar.bz2)
          echo "Installing package: $PACKAGE_FILE"
          conda install $PACKAGE_FILE -y
  
      - name: Test import
        shell: bash -l {0}
        run: |
          python -c "import map2loop"
