name: Test Conda Build and Import

on:
  push:
  workflow_dispatch:

jobs:
  test-conda-build:
    name: Test Conda Build and Import
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.1.0
        with:
          miniforge-version: latest

      - name: Install conda-build
        shell: bash -l {0}
        run: |
          conda update -n base conda -y
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda install conda-build -y

      - name: Build conda package
        shell: bash -l {0}
        run: |
          conda build -c conda-forge -c loop3d -c anaconda conda 

      - name: Install map2loop
        shell: bash -l {0}
        run: |
          conda install -c local --use-local map2loop -y
  
      - name: Test import
        shell: bash -l {0}
        run: |
          python -c "import map2loop"
